### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by NhanAZ** [kaidoMC/ItemFactory#5]
> Nothing in plugin file, doesn’t work - Tuvqlu
https://discord.com/channels/373199722573201408/713715603239862353/939780559079632937

**Comment by NhanAZ** [comment]
@Tuvqlu
Can you describe the problem you are having?
This plugin has been thoroughly tested by me and has no problems.

**Comment by Tuvqlu** [comment]
When I open the file in plug-in data, it’s empty 
![1DE99D20-6943-46AE-94EC-1E88F98D93E1](https://user-images.githubusercontent.com/98550458/153279624-fa478442-43d7-4e99-8018-7273a22d402b.jpeg)

**Comment by NguyenDuck** [comment]
Run server for plugin loaded ( whitelist all plugin )

**Comment by Tuvqlu** [comment]
What do you mean?

**Comment by NhanAZ** [comment]
@Tuvqlu 
This plugin has nothing to store in plugin_data so plugin_data is empty...
To use this plugin you can read the instructions below.
```
Enter the command /ifa to open the main interface of the Plugin. The interface includes buttons:

Create - To create an item of your choice.
Clone - Copy the item you are holding in your hand.
Edit - Edit the item you are holding in your hand.
```
I bet this is not a bug... Can you correct your review on poggit? I think it's a hasty review!

**Comment by Tuvqlu** [comment]
Yes, but I tried /ifa in game, and it did not exist.

**Comment by NhanAZ** [comment]
Looks like your server is installing a lot of plugins.
This can lead to duplicate commands and some commands won't work!

**Comment by NhanAZ** [comment]
This does not appear to be an error.
Please allow me to close this issue.
Thanks for the review @Tuvqlu

**Comment by Tuvqlu** [comment]
Okay, thankyou.
